---
dependencies:
  cloud_firestore: ^5.0.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  cross_file_image: ^1.1.0
  dash_chat_2: ^0.0.21
  flutter:
    sdk: flutter
  flutter_gemini: ^2.0.4
  flutter_markdown: ^0.7.2
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  markdown: ^7.2.2
  open_file: ^3.3.2
  path_provider: ^2.1.3
  pdf: ^3.10.8
  printing: ^5.12.0
  provider: ^6.1.2
  connectivity_plus: ^6.0.3
  flutter_bloc: ^8.1.6
  number_editing_controller: ^1.3.1
description: A new Flutter project.
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.3.4 <4.0.0'
flutter:
  assets:
      - assets/
  uses-material-design: true
name: user
publish_to: none
version: 1.0.0+1