// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:130357781047:web:7369bee52b171f7c9015b2',
    messagingSenderId: '130357781047',
    projectId: 'user-19315',
    authDomain: 'user-19315.firebaseapp.com',
    storageBucket: 'user-19315.appspot.com',
    measurementId: 'G-9K938LRESP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:130357781047:android:7c8edd580f4f07339015b2',
    messagingSenderId: '130357781047',
    projectId: 'user-19315',
    storageBucket: 'user-19315.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:130357781047:ios:480d0d9e463f3b279015b2',
    messagingSenderId: '130357781047',
    projectId: 'user-19315',
    storageBucket: 'user-19315.appspot.com',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:130357781047:ios:480d0d9e463f3b279015b2',
    messagingSenderId: '130357781047',
    projectId: 'user-19315',
    storageBucket: 'user-19315.appspot.com',
    iosBundleId: 'com.example.user',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:130357781047:web:afc80c4a30174d279015b2',
    messagingSenderId: '130357781047',
    projectId: 'user-19315',
    authDomain: 'user-19315.firebaseapp.com',
    storageBucket: 'user-19315.appspot.com',
    measurementId: 'G-NQBLFE1224',
  );
}
